export const INCREEMENT_COUNTE ="INCREEMENT_COUNTE"
export const DECREEMENT_COUNTE ="DECREEMENT_COUNTE"

export const GET_MEDICINE="GET_MEDICINE"
export const LOADING_MEDICINE="LOADING_MEDICINE"
export const ERROR_MEDICINE="ERROR_MEDICINE"
